apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8082
      targetPort: 8082
    - name: jnlp
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins