apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
  labels:
    app: grafana
spec:
  type: LoadBalancer
  ports:
    - port: 80         # External port
      targetPort: 3000 # Internal port (Grafana default port)
  selector:
    app: grafana
