apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#kubernetes resources to be managed by kustomize
resources:
  - deployment.yaml

#Customizations that need to be made
commonLabels:
  company: KodeKloud